indicators_api_url="https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicators/" # https://datos.canarias.es/api/estadisticas/indicators/v1.0/indicators/
default_geographical_location = "Canarias" # Localizacion por defecto en caso de que el usuario no proporcione ninguna. Ej. Canarias
similar_indicators_quantity = 5 # Número de indicadores similares que se devuelve al usuario.
locale = "es_ES.UTF-8" # Ej. es_ES.UTF-8
logs_path = "/data/istac/istacbot/logs/" # Ej. /data/istac/istacbot/logs/
dataset_path = './data'
chatito_path = './data/chatito/'
discard_messages_timemout = 5 # Descartar mensajes que se hayan emitido pasados los minutos especificados. Ej. 5
duckling_server="http://192.168.1.168:8000/parse" # Ej. http://192.168.1.168:8000/parse
telegram_access_token="¨FILL_TELEGRAM_TOKEN" # Token proporcianado por Telegram
telegram_verify="FILL_TELEGRAM_BOT_NAME" # Ej. testistacbot
telegram_webhook_url="FILL_TELEGRAM_WEBHOOK" # Ej. https://bots.arte-consultores.com/istac_bot
telegram_webhook_port = "FILL_TELEGRAM_WEBHOOK_PORT" # Ej.5004
facebook_webhook_port = "FILL_FACEBOOK_WEBHOOK_PORT" # Ej.5004
facebook_verify = "FILL_FACEBOOK_BOT_NAME" #Ej. testistacbot
facebook_secret = "FILL_FACEBOOK_SECRET" # Secreto proporcionado por Facebook
facebook_token = "FILL_FACEBOOK_TOKEN" #Token proporcionado por Facebook
