url="FILL_API_ISTAC_URL" # https://www3.gobiernodecanarias.org/istac/api/indicators/v1.0/indicators/
default_location = "FILL_DEFAULT_LOCATION" # Localizacion por defecto en caso de que el usuario no proporcione ninguna. Ej. Canarias
number_similar_indicators = "FILL_NUMBER_SIMILAR_INDICATORS" # Número de indicadores similares que se devuelve al usuario.
locale = "FILL_LOCALE" # Ej. es_ES.UTF-8
location = "FILL_LOCATION_LOG" # Ej. /data/istac/istacbot/logs/
discard_messages_max_minutes = "FILL_MINUTES" # Descartar mensajes que se hayan emitido pasados los minutos especificados. Ej. 5
duckling_server="FILL_URL_DUCKLING" # Ej. http://192.168.1.168:8000/parse
telegram_access_token="¨FILL_TELEGRAM_TOKEN"
telegram_verify="FILL_TELEGRAM_BOT_NAME"
telegram_webhook_url="FILL_TELEGRAM_WEBHOOK"
webhook_port = "FILL_TELEGRAM_WEBHOOK_PORT" # Ej.5004
facebook_verify = "FILL_FACEBOOK_BOT_NAME"
facebook_secret = "FILL_FACEBOOK_SECRET"
facebook_token = "FILL_TOKEN"
