indicators_api_url="https://www3.gobiernodecanarias.org/istac/api/indicators/v1.0/indicators/" # https://www3.gobiernodecanarias.org/istac/api/indicators/v1.0/indicators/
default_geographical_location = "Canarias" # Localizacion por defecto en caso de que el usuario no proporcione ninguna. Ej. Canarias
similar_indicators_quantity = 5 # Número de indicadores similares que se devuelve al usuario.
locale = "es_ES.UTF-8" # Ej. es_ES.UTF-8
logs_path = "/data/istac/istacbot/logs/" # Ej. /data/istac/istacbot/logs/
discard_messages_timemout = 5 # Descartar mensajes que se hayan emitido pasados los minutos especificados. Ej. 5
duckling_server="http://192.168.1.168:8000/parse" # Ej. http://192.168.1.168:8000/parse
telegram_access_token="¨FILL_TELEGRAM_TOKEN"
telegram_verify="FILL_TELEGRAM_BOT_NAME"
telegram_webhook_url="FILL_TELEGRAM_WEBHOOK"
telegram_webhook_port = "FILL_TELEGRAM_WEBHOOK_PORT" # Ej.5004
facebook_webhook_port = "FILL_TELEGRAM_WEBHOOK_PORT" # Ej.5004
facebook_verify = "FILL_FACEBOOK_BOT_NAME"
facebook_secret = "FILL_FACEBOOK_SECRET"
facebook_token = "FILL_TOKEN"
