# coding=utf-8

indicators = {
    'Afiliaciones a la Seguridad Social': 'AFILIACIONES',
    'Venta mayor de cemento': 'CEMENTO_VENTAS',
    'Empleo registrado. Agricultura': 'EMPLEO_REGISTRADO_AGRICULTURA',
    'Empleo registrado. Hostelería': 'EMPLEO_REGISTRADO_HOSTELERIA',
    'Empleo registrado. Industria': 'EMPLEO_REGISTRADO_INDUSTRIA',
    'Empleo registrado. Servicios': 'EMPLEO_REGISTRADO_SERVICIOS',
    'Población inactiva': 'POBLACION_INACTIVA',
    'Población inactiva. Hombres': 'POBLACION_INACTIVA_HOMBRES',
    'Población inactiva. Mujeres': 'POBLACION_INACTIVA_MUJERES',
    'Tasa de actividad': 'TASA_ACTIVIDAD',
    'Tasa de actividad. Hombres': 'TASA_ACTIVIDAD_HOMBRES',
    'Tasa de actividad. Mujeres': 'TASA_ACTIVIDAD_MUJERES',
    'Tasa de empleo': 'TASA_EMPLEO',
    'Tasa de empleo. Hombres': 'TASA_EMPLEO_HOMBRES',
    'Tasa de empleo. Mujeres': 'TASA_EMPLEO_MUJERES',
    'Tasa de paro': 'TASA_PARO',
    'Tasa de paro. Hombres': 'TASA_PARO_HOMBRES',
    'Tasa de paro. Mujeres': 'TASA_PARO_MUJERES',
    'Paro registrado': 'PARO_REGISTRADO',
    'Paro registrado. Hombres': 'PARO_REGISTRADO_HOMBRES',
    'Paro registrado. Mujeres': 'PARO_REGISTRADO_MUJERES',
    'Nacimientos': 'NACIMIENTOS',
    'Defunciones': 'DEFUNCIONES',
    'Población. Edad media': 'POBLACION_EDAD_MEDIA',
    'Población. De 0 a 14 años (% sobre total)': 'POBLACION_00A14_PC',
    'Población. De 65 o más años (% sobre total)': 'POBLACION_65MAS_PC',
    'Defunciones. Mujeres': 'DEFUNCIONES_MUJERES',
    'Nacimientos. Hombres': 'NACIMIENTOS_HOMBRES',
    'Nacimientos. Mujeres': 'NACIMIENTOS_MUJERES',
    'Pernoctaciones en alojamientos turísticos': 'ALOJATUR_PERNOCTACIONES',
    'Plazas ofertadas por alojamientos turísticos': 'ALOJATUR_PLAZAS_OFERTADAS',
    'Población': 'POBLACION',
    'Población. De 0 a 14 años': 'POBLACION_00A14',
    'Población. De 15 a 64 años': 'POBLACION_15A64',
    'Población. De 15 a 64 años. Hombres': 'POBLACION_HOMBRES_15A64',
    'Población. De 65 o más años': 'POBLACION_65MAS',
    'Población. Hombres': 'POBLACION_HOMBRES',
    'Población. Mujeres': 'POBLACION_MUJERES',
    'Población. De 0 a 14 años. Hombres': 'POBLACION_HOMBRES_00A14',
    'Población. De 0 a 14 años. Mujeres': 'POBLACION_MUJERES_00A14',
    'Población. De 65 o más años. Mujeres': 'POBLACION_MUJERES_65MAS',
    'Matriculación de vehículos': 'MATRICULA_VEHICULOS',
    'Matriculación de vehículos. Turismos': 'MATRICULA_VEHICULOS_TURISMOS',
    'Policía Local. Efectivos': 'POLICIA_LOCAL_EFECTIVOS',
    'Viajeros entrados en alojamientos turísticos': 'ALOJATUR_VIAJEROS_ENTRADOS',
    'Empleo registrado. Cabildos': 'EMPLEO_REGISTRADO_CABILDOS',
    'Empleo registrado por cada 1.000 habitantes. Cabildos': 'EMPLEO_REGISTRADO_CABILDOS_HAB',
    'IRPF. Base Imponible por declarante': 'TRIBUTO_IRPF_BASE_IMPONIBLE_DECLARANTE',
    'IBI. Cuota líquida. Urbanos': 'TRIBUTO_IBI_CUOTA_LIQUIDA_URBANO',
    'IBI. Cuota líquida. Rústicos': 'TRIBUTO_IBI_CUOTA_LIQUIDA_RUSTICO',
    'Presupuesto liquidado. Gastos por habitante. Ayuntamientos': 'PRESUPUESTO_AYUNTAMIENTOS_LIQUIDADO_GASTO_HABITANTE',
    'Presupuesto liquidado. Ingresos por habitante. Ayuntamientos': 'PRESUPUESTO_AYUNTAMIENTOS_LIQUIDADO_INGRESO_HABITANTE',
    'Presupuesto liquidado. Ingresos fiscales por habitante. Ayuntamientos': 'PRESUPUESTO_AYUNTAMIENTOS_LIQUIDADO_INGRESO_FISCAL_HABITANTE',
    'Presupuesto liquidado. Gastos por habitante. Cabildos': 'PRESUPUESTO_CABILDOS_LIQUIDADO_GASTO_HABITANTE',
    'Presupuesto liquidado. Ingresos por habitante. Cabildos': 'PRESUPUESTO_CABILDOS_LIQUIDADO_INGRESO_HABITANTE',
    'Presupuesto liquidado. Ingresos fiscales por habitante. Cabildos': 'PRESUPUESTO_CABILDOS_LIQUIDADO_INGRESO_FISCAL_HABITANTE',
    'Población. De 65 o más años. Hombres': 'POBLACION_HOMBRES_65MAS',
    'Población. De 15 a 64 años. Mujeres': 'POBLACION_MUJERES_15A64',
    'Matrimonios. Entre cónyuges de diferente sexo': 'MATRIMONIOS_SEXO_DIFERENTE',
    'Defunciones. Hombres': 'DEFUNCIONES_HOMBRES',
    'Migraciones. Saldo migratorio': 'MIGRACIONES_SALDO',
    'Migraciones. Saldo migratorio. Hombres': 'MIGRACIONES_SALDO_HOMBRES',
    'Migraciones. Saldo migratorio. Mujeres': 'MIGRACIONES_SALDO_MUJERES',
    'Policía Local. Efecticvos por cada 1.000 habitantes': 'POLICIA_LOCAL_EFECTIVOS_HABITANTE',
    'Parque de vehículos': 'PARQUE_VEHICULOS',
    'Parque de vehículos. Turismos': 'PARQUE_VEHICULOS_TURISMOS',
    'Tráfico aéreo comercial. Movimiento de mercancías': 'TRAFICO_AEREO_MERCANCIAS',
    'Superficie cultivada': 'SUPERFICIE_CULTIVO',
    'Superficie cultivada. Regadío': 'SUPERFICIE_CULTIVO_REGADIO',
    'Superficie cultivada. Cultivos herbáceos': 'SUPERFICIE_CULTIVO_HERBACEOS',
    'Superficie cultivada. Cultivos leñosos': 'SUPERFICIE_CULTIVO_LENOSOS',
    'Tasa bruta de mortalidad': 'TASA_MORTALIDAD',
    'Población parada': 'POBLACION_PARADA',
    'Población parada. Hombres': 'POBLACION_PARADA_HOMBRES',
    'Población parada. Mujeres': 'POBLACION_PARADA_MUJERES',
    'Población ocupada': 'POBLACION_OCUPADA',
    'Población ocupada. Hombres': 'POBLACION_OCUPADA_HOMBRES',
    'Población ocupada. Mujeres': 'POBLACION_OCUPADA_MUJERES',
    'Población turística equivalente en alojamientos turísticos': 'ALOJATUR_POBLACION_TUR_ETC',
    'Empleo registrado. Ayuntamientos': 'EMPLEO_REGISTRADO_AYUNTAMIENTOS',
    'Empleo registrado por cada 1.000 habitantes. Ayuntamientos': 'EMPLEO_REGISTRADO_AYUNTAMIENTOS_HAB',
    'Parque de vehículos por cada 1.000 habitantes': 'PARQUE_VEHICULOS_HABITANTE',
    'Parque de vehículos por cada 1.000 habitantes. Turismos': 'PARQUE_VEHICULOS_TURISMOS_HABITANTE',
    'Tráfico aéreo comercial. Movimiento de aeronaves': 'TRAFICO_AEREO_AVIONES',
    'Tráfico aéreo comercial. Movimiento de pasajeros': 'TRAFICO_AEREO_PASAJEROS',
    'Superficie cultivada. Secano': 'SUPERFICIE_CULTIVO_SECANO',
    'Superficie': 'SUPERFICIE',
    'Alojamientos turísticos abiertos': 'ALOJATUR_ABIERTOS',
    'Empleo registrado. Comercio': 'EMPLEO_REGISTRADO_COMERCIO',
    'Empleo registrado. Construcción': 'EMPLEO_REGISTRADO_CONSTRUCCION',
    'Población activa': 'POBLACION_ACTIVA',
    'Población activa. Hombres': 'POBLACION_ACTIVA_HOMBRES',
    'Población activa. Mujeres': 'POBLACION_ACTIVA_MUJERES',
    'Afiliaciones a la Seguridad Social. Hombres': 'AFILIACIONES_HOMBRES',
    'Afiliaciones a la Seguridad Social. Mujeres': 'AFILIACIONES_MUJERES',
    'Afiliaciones a la Seguridad Social. Empleos asalariados. Hombres': 'AFILIACIONES_ASALARIADOS_HOMBRES',
    'Afiliaciones a la Seguridad Social. Empleos asalariados': 'AFILIACIONES_ASALARIADOS',
    'Afiliaciones a la Seguridad Social. Empleos asalariados. Mujeres': 'AFILIACIONES_ASALARIADOS_MUJERES',
    'Afiliaciones a la Seguridad Social. Empleos autónomos': 'AFILIACIONES_AUTONOMOS',
    'Afiliaciones a la Seguridad Social. Empleos autónomos. Hombres': 'AFILIACIONES_AUTONOMOS_HOMBRES',
    'Afiliaciones a la Seguridad Social. Empleos autónomos. Mujeres': 'AFILIACIONES_AUTONOMOS_MUJERES',
    'Índice de precios de consumo (IPC). Subyacente': 'IPC_SUBYACENTE',
    'Tasa bruta de mortalidad. Hombres': 'TASA_MORTALIDAD_HOMBRES',
    'Tasa bruta de mortalidad. Mujeres': 'TASA_MORTALIDAD_MUJERES',
    'Comercio exterior. Importaciones en peso': 'COMERCIO_EXTERIOR_IMPORTACIONES_PESO',
    'Comercio exterior. Importaciones en valor': 'COMERCIO_EXTERIOR_IMPORTACIONES_VALOR',
    'Comercio exterior. Exportaciones en peso': 'COMERCIO_EXTERIOR_EXPORTACIONES_PESO',
    'Comercio exterior. Exportaciones en valor': 'COMERCIO_EXTERIOR_EXPORTACIONES_VALOR',
    'Comercio exterior. Déficit comercial': 'COMERCIO_EXTERIOR_DEFICIT_COMERCIAL',
    'Comercio exterior. Tasa de cobertura': 'COMERCIO_EXTERIOR_TASA_COBERTURA',
    'PIB a precios corrientes': 'PIB_PM_CORRIENTE',
    'Energía eléctrica. Disponible': 'ENERGIA_ELECTRICA_DISPONIBLE',
    'Coste laboral. Por trabajador y mes': 'COSTE_LABORAL_TRABAJADOR',
    'Coste laboral. Por hora efectiva de trabajo': 'COSTE_LABORAL_HORA',
    'Hipotecas constituidas': 'HIPOTECAS_CONSTITUIDAS',
    'Hipotecas constituidas. Importe': 'HIPOTECAS_CONSTITUIDAS_IMPORTE',
    'Hipotecas canceladas': 'HIPOTECAS_CANCELADAS',
    'Índice de volumen encadenado del PIB (variaciones reales)': 'PIB_PM_VOLUMEN',
    'Sociedades mercantiles. Creadas': 'SOCIEDADES_MERCANTILES_CREADAS',
    'Sociedades mercantiles. Creadas. Capital suscrito': 'SOCIEDADES_MERCANTILES_CREADAS_CAPITAL',
    'Sociedades mercantiles. Amplian capital': 'SOCIEDADES_MERCANTILES_AMPLIADAS',
    'Sociedades mercantiles. Amplian capital. Capital suscrito': 'SOCIEDADES_MERCANTILES_AMPLIADAS_CAPITAL',
    'Licitación oficial en construcción': 'LICITACION_OFICIAL',
    'Licitación oficial en construcción. Edificación': 'LICITACION_OFICIAL_EDIFICACION',
    'Licitación oficial en construcción. Ingeniería civil': 'LICITACION_OFICIAL_INGENIERIA_CIVIL',
    'Afiliaciones a la Seguridad Social. Industria': 'AFILIACIONES_INDUSTRIA',
    'Afiliaciones a la Seguridad Social. Construcción': 'AFILIACIONES_CONSTRUCCION',
    'Afiliaciones a la Seguridad Social. Servicios': 'AFILIACIONES_SERVICIOS',
    'Afiliaciones a la Seguridad Social. Agricultura': 'AFILIACIONES_AGRICULTURA',
    'Accidentes de trabajo con baja': 'ACCIDENTES_TRABAJO_BAJA',
    'Accidentes de trabajo con baja. Jornadas no trabajadas': 'ACCIDENTES_TRABAJO_BAJA_JORNADAS',
    'Empresas inscritas en la Seguridad Social. Agricultura': 'EMPRESAS_SEGURIDAD_SOCIAL_AGRICULTURA',
    'Empresas inscritas en la Seguridad Social. Industria': 'EMPRESAS_SEGURIDAD_SOCIAL_INDUSTRIA',
    'Empresas inscritas en la Seguridad Social. Construcción': 'EMPRESAS_SEGURIDAD_SOCIAL_CONSTRUCCION',
    'Empresas inscritas en la Seguridad Social. Servicios': 'EMPRESAS_SEGURIDAD_SOCIAL_SERVICIOS',
    'Visados de obra. Viviendas': 'VISADOS_OBRA_VIVIENDAS',
    'Visados de obra. Viviendas de obra nueva': 'VISADOS_OBRA_VIVIENDAS_NUEVAS',
    'Vivienda libre. Precio del metro cuadrado': 'VIVIENDA_LIBRE_PRECIO_M2',
    'Vivienda protegida. Precio del metro cuadrado': 'VIVIENDA_PROTEGIDA_PRECIO_M2',
    'Empresas inscritas en la Seguridad Social': 'EMPRESAS_SEGURIDAD_SOCIAL',
    'IBI. Tipo de gravamen. Rústicos': 'TRIBUTO_IBI_TIPO_GRAVAMEN_RUSTICO',
    'IBI. Tipo de gravamen. Urbanos': 'TRIBUTO_IBI_TIPO_GRAVAMEN_URBANO',
    'Cabezas de ganado. Bovino': 'GANADO_BOVINO',
    'Cabezas de ganado. Caprino': 'GANADO_CAPRINO',
    'Cabezas de ganado. Ovino': 'GANADO_OVINO',
    'Cabezas de ganado. Porcino': 'GANADO_PORCINO',
    'Tasa de ocupación por plazas': 'ALOJATUR_PLAZAS_OCUPACION',
    'Gasto turístico': 'GASTO_TURISTICO',
    'Gasto medio por turista': 'GASTO_TURISTICO_TURISTA',
    'Gasto medio por turista y día': 'GASTO_TURISTICO_TURISTA_DIA',
    'Población extranjera': 'POBLACION_EXTRANJERA',
    'Población extranjera. Hombres': 'POBLACION_EXTRANJERA_HOMBRES',
    'Población extranjera. Mujeres': 'POBLACION_EXTRANJERA_MUJERES',
    'Índice de precios industriales': 'IPRI',
    'Índice de producción industrial': 'IPI',
    'Índice de precios de consumo (IPC). General': 'IPC',
    'Alumnado no universitario. Enseñanzas de régimen general': 'ALUMNADO_NO_UNIVERSITARIO_REGIMEN_GENERAL',
    'Alumnado no universitario. Educación primaria': 'ALUMNADO_NO_UNIVERSITARIO_REGIMEN_GENERAL_PRIMARIA',
    'Alumnado no universitario. Educación secundaria obligatoria (E.S.O)': 'ALUMNADO_NO_UNIVERSITARIO_REGIMEN_GENERAL_ESO',
    'Alumnado no universitario. Centros públicos. Enseñanzas de régimen general': 'ALUMNADO_NO_UNIVERSITARIO_PUBLICOS_REGIMEN_GENERAL',
    'Alumnado no universitario. Centros privados concertados. Enseñanzas de régimen general': 'ALUMNADO_NO_UNIVERSITARIO_CONCERTADOS_REGIMEN_GENERAL',
    'Alumnado no universitario. Centros privados no concertados. Enseñanzas de régimen general': 'ALUMNADO_NO_UNIVERSITARIO_NO_CONCERTADOS_REGIMEN_GENERAL',
    'Alumnado no universitario. Educación infantil': 'ALUMNADO_NO_UNIVERSITARIO_REGIMEN_GENERAL_INFANTIL',
    'Índice de cifra de negocios. Servicios': 'IASS_CIFRA_NEGOCIO',
    'Indice de ocupación (IASS). Servicios': 'IASS_OCUPACION',
    'Comercio exterior. Importaciones en peso. Productos agrícolas': 'COMERCIO_EXTERIOR_IMPORTACIONES_PESO_AGRICOLAS',
    'Comercio exterior. Importaciones en valor. Productos agrícolas': 'COMERCIO_EXTERIOR_IMPORTACIONES_VALOR_AGRICOLAS',
    'Comercio exterior. Exportaciones en peso. Productos agrícolas': 'COMERCIO_EXTERIOR_EXPORTACIONES_PESO_AGRICOLAS',
    'Comercio exterior. Exportaciones en valor. Productos agrícolas': 'COMERCIO_EXTERIOR_EXPORTACIONES_VALOR_AGRICOLAS',
    'Empleo registrado': 'EMPLEO_REGISTRADO',
    'Empleo registrado. Autónomos': 'EMPLEO_REGISTRADO_AUTONOMOS',
    'Empleo registrado. Asalariados': 'EMPLEO_REGISTRADO_ASALARIADOS'
}

locations_check = {
    "Canarias",
    "Arrecife",
    "Haría",
    "San Bartolomé",
    "Teguise",
    "Tías",
    "Tinajo",
    "Yaiza",
    "Antigua",
    "Betancuria",
    "Oliva",
    "Pájara",
    "Puerto del Rosario",
    "Tuineje",
    "Agaete",
    "Agüimes"
    "Artenara",
    "Arucas",
    "Firgas",
    "Gáldar",
    "Ingenio",
    "Mogán",
    "Moya",
    "Palmas de Gran Canaria",
    "San Bartolomé de Tirajana",
    "Aldea de San Nicolás",
    "Santa Brígida",
    "Santa Lucía de Tirajana",
    "Santa María de Guía de Gran Canaria",
    "Tejeda",
    "Telde",
    "Teror",
    "Valsequillo de Gran Canaria",
    "Valleseco",
    "Vega de San Mateo",
    "Adeje",
    "Arafo",
    "Arico",
    "Arona",
    "Buenavista del Norte",
    "Candelaria",
    "Fasnia",
    "Garachico",
    "Granadilla de Abona",
    "Guancha",
    "Guía de Isora",
    "Güímar",
    "Icod de los Vinos",
    "San Cristóbal de La Laguna",
    "Matanza de Acentejo",
    "Orotava",
    "Puerto de La Cruz",
    "Realejos",
    "Rosario",
    "San Juan de la Rambla",
    "San Miguel de Abona",
    "Santa Úrsula",
    "Santiago del Teide",
    "Sauzal",
    "Silos",
    "Tacoronte",
    "Tanque",
    "Tegueste",
    "Victoria de Acentejo",
    "Vilaflor de Chasna",
    "Agulo",
    "Alajeró",
    "Hermigua",
    "San Sebastián de La Gomera",
    "Valle Gran Rey",
    "Vallehermoso",
    "Barlovento",
    "Breña Alta",
    "Breña Baja",
    "Fuencaliente de La Palma",
    "Garafía",
    "Llanos de Aridane",
    "Paso",
    "Puntagorda",
    "Puntallana",
    "San Andrés y Sauces",
    "Santa Cruz de La Palma",
    "Tazacorte",
    "Tijarafe",
    "Villa de Mazo",
    "Frontera",
    "Valverde",
    "Pinar de El Hierro",
    "Lanzarote",
    "Gran Canaria",
    "Tenerife",
    "La Gomera",
    "La Palma",
    "El Hierro",
    "Ceuta y Melilla",
    "Andalucía",
    "Aragón",
    "Principado de Asturias",
    "Illes Balears",
    "Cantabria",
    "Castilla y León",
    "Castilla - La Mancha",
    "Cataluña",
    "Comunitat Valenciana",
    "Extremadura",
    "Galicia",
    "Comunidad de Madrid",
    "Madrid",
    "Región de Murcia",
    "Comunidad Foral de Navarra",
    "Navarra",
    "País Vasco",
    "Rioja",
    "Ceuta",
    "Melilla",
    "Albacete",
    "Alacant",
    "Alicante",
    "Almería",
    "Araba",
    "Álava",
    "Asturias",
    "Ávila",
    "Badajoz",
    "Illes Balears",
    "Balears",
    "Islas Baleares",
    "Baleares",
    "Barcelona",
    "Bizkaia",
    "Burgos",
    "Cáceres",
    "Cádiz",
    "Cantabria",
    "Castelló",
    "Castellón",
    "Ceuta",
    "Ciudad Real",
    "Córdoba",
    "Coruña",
    "A Coruña",
    "Cuenca",
    "Gipuzkoa",
    "Girona",
    "Gerona",
    "Granada",
    "Guadalajara",
    "Huelva",
    "Huesca",
    "Jaén",
    "León",
    "Lleida",
    "Lérida",
    "Lugo",
    "Madrid",
    "Málaga",
    "Melilla",
    "Murcia",
    "Navarra",
    "Ourense",
    "Palencia",
    "Palmas",
    "Pontevedra",
    "Rioja",
    "Salamanca",
    "Santa Cruz de Tenerife",
    "Segovia",
    "Sevilla",
    "Soria",
    "Tarragona",
    "Teruel",
    "Toledo",
    "Valladolid",
    "Zamora",
    "Zaragoza",
    "València",
    "Valencia",
    "Lanzarote",
    "Lanzarote - Este",
    "Lanzarote - Norte",
    "Lanzarote - Suroeste",
    "Fuerteventura",
    "Fuerteventura - Centro",
    "Fuerteventura - Norte",
    "Fuerteventura - Sur",
    "Gran Canaria - Área Metropolitana",
    "Gran Canaria - Área Metropolitana",
    "Gran Canaria - Norte",
    "Gran Canaria Norte - Centro Norte",
    "Gran Canaria Norte - Noroeste",
    "Gran Canaria Norte - Oeste",
    "Gran Canaria - Sur",
    "Gran Canaria Sur - Sur",
    "Gran Canaria Sur - Sureste",
    "Tenerife - Área Metropolitana",
    "Tenerife - Área Metropolitana",
    "Tenerife - Norte",
    "Tenerife Norte - Acentejo",
    "Tenerife Norte - Daute",
    "Tenerife Norte - Icod",
    "Tenerife Norte - Valle de La Orotava",
    "Tenerife - Sur",
    "Tenerife Sur - Abona",
    "Tenerife Sur - Suroeste",
    "Tenerife Sur - Valle de Güímar",
    "La Gomera",
    "La Gomera - Norte",
    "La Gomera - Sur",
    "La Palma",
    "La Palma - Capitalina",
    "La Palma - Noreste",
    "La Palma - Noroeste",
    "La Palma - Valle de Aridane",
    "El Hierro",
    "El Hierro - El Hierro",
    "España"
}

hombres_indicadores = {
    'Población inactiva. Hombres': 'POBLACION_INACTIVA_HOMBRES',
    'Tasa de empleo. Hombres': 'TASA_EMPLEO_HOMBRES',
    'Tasa de paro. Hombres': 'TASA_PARO_HOMBRES',
    'Paro registrado. Hombres': 'PARO_REGISTRADO_HOMBRES',
    'Nacimientos. Hombres': 'NACIMIENTOS_HOMBRES'
}

mujeres_indicadores = {
    'Población inactiva. Mujeres': 'POBLACION_INACTIVA_MUJERES',
    'Tasa de empleo. Mujeres': 'TASA_EMPLEO_MUJERES',
    'Tasa de paro. Mujeres': 'TASA_PARO_MUJERES',
    'Paro registrado. Mujeres': 'PARO_REGISTRADO_MUJERES',
    'Defunciones. Mujeres': 'DEFUNCIONES_MUJERES'
}

indicators_with_sex = [
    "Población inactiva",
    "Tasa de actividad",
    "Tasa de empleo",
    "Tasa de paro",
    "Paro registrado",
    "Defunciones",
    "Nacimientos",
    "Población",
    "Defunciones",
    "Migraciones. Saldo migratorio",
    "Población parada",
    "Población ocupada",
    "Población activa",
    "Afiliaciones a la Seguridad Social",
    "Afiliaciones a la Seguridad Social. Empleos asalariados",
    "Afiliaciones a la Seguridad Social. Empleos autónomos",
    "Tasa bruta de mortalidad",
    "Población extranjera"
]

months ={
    "enero": "m01",
    "febrero": "m02",
    "marzo": "m03",
    "abril": "m04",
    "mayo": "m05",
    "junio": "m06",
    "julio": "m07",
    "agosto": "m08",
    "septiembre": "m09",
    "octubre": "m10",
    "noviembre": "m11",
    "diciembre": "m12"
}